/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Liveness check. See /docs for the full API reference.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio Command aggregates
         * @description Total expected loss, risk-tier breakdown, flagged-loan count/pct,
         *     anomaly rate and count by region and loan_type, reviewer override rate,
         *     and -- if a scenario has been run -- the baseline-vs-shocked expected
         *     loss comparison. See portfolio/summary.py for the exact definitions
         *     (in particular, what "the portfolio" means here: the current book under
         *     active servicing, i.e. the time-aware test split).
         */
        get: operations["portfolio_summary_portfolio_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Paginated, filterable loan list
         * @description Summary rows for the current book -- no SHAP or reviewer note here
         *     (that's GET /loans/{loan_id}); this endpoint is meant to back a fast,
         *     filterable list/table view.
         */
        get: operations["list_loans_loans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loans/{loan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full record for one loan
         * @description Prediction, calibrated probability, anomaly flag, SHAP top features,
         *     reviewer note, and audit history for one loan.
         *
         *     Scores the loan live against the already-trained models (no retraining)
         *     the first time it's viewed, logging that scoring to the audit trail if
         *     it isn't already there -- the same idempotent-on-first-view behavior
         *     review/decisions.py uses. The reviewer note is likewise generated once
         *     (via Gemini, or the template fallback with no API key set) and reused
         *     on subsequent views rather than re-called every request.
         */
        get: operations["get_loan_loans__loan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loans/{loan_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a reviewer decision
         * @description Accept or override the current flag on a loan. Rejected (400) if the
         *     loan isn't currently flagged -- there's nothing to review. Never
         *     mutates the underlying prediction or anomaly score; logs a new,
         *     hash-chained reviewer_decision entry that references the flag entry it
         *     responds to. See review/decisions.py.
         */
        post: operations["review_loan_loans__loan_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenario/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a portfolio scenario shock
         * @description Shocks a feature (interest_rate: +/- percentage points; dti: +/-
         *     fraction e.g. 0.15; regional_income: +/-% income change, optionally
         *     scoped to one region) across the full portfolio and returns the
         *     before/after expected loss. Persists the same plot/CSV/summary
         *     artifacts `python -m loan_intelligence.scenario.simulate` would from
         *     the CLI, and logs the run to the audit trail.
         */
        post: operations["scenario_run_scenario_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify the hash chain
         * @description Re-verifies the full SHA-256 hash chain from genesis. Returns
         *     {"valid": true, "n_entries": N} or {"valid": false, "broken_at_id": id,
         *     "reason": ...} at the first link that doesn't reproduce.
         */
        get: operations["audit_verify_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every audit entry
         * @description Every entry in the hash chain, oldest first -- the raw sequence
         *     verify() walks. For visualizing the chain itself (nodes, links, which
         *     entry references which); GET /audit/verify stays the lightweight
         *     valid/broken check for anything that just needs a status.
         */
        get: operations["audit_entries_audit_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnomalyBreakdown */
        AnomalyBreakdown: {
            /** Overall Rate */
            overall_rate: number;
            /** Overall Count */
            overall_count: number;
            /** Lift */
            lift?: number | null;
            /** By Region */
            by_region: {
                [key: string]: components["schemas"]["GroupStat"];
            };
            /** By Loan Type */
            by_loan_type: {
                [key: string]: components["schemas"]["GroupStat"];
            };
        };
        /** AuditEntry */
        AuditEntry: {
            /** Id */
            id: number;
            /** Timestamp */
            timestamp: string;
            /** Event Type */
            event_type: string;
            /** Loan Id */
            loan_id?: string | null;
            /** References Hash */
            references_hash: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Entry Hash */
            entry_hash: string;
        };
        /** AuditVerifyResponse */
        AuditVerifyResponse: {
            /** Valid */
            valid: boolean;
            /** N Entries */
            n_entries?: number | null;
            /** Broken At Id */
            broken_at_id?: number | null;
            /** Reason */
            reason?: string | null;
        };
        /** GroupStat */
        GroupStat: {
            /** Count */
            count: number;
            /** Rate */
            rate: number;
        };
        /** HTTPError */
        HTTPError: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /** Status */
            status: string;
        };
        /** LoanDetailResponse */
        LoanDetailResponse: {
            /** Loan Id */
            loan_id: string;
            /** Region */
            region: string;
            /** Loan Type */
            loan_type: string;
            /** Loan Amount */
            loan_amount: number;
            /** Raw Probability */
            raw_probability: number;
            /** Calibrated Probability */
            calibrated_probability: number;
            /** Risk Tier */
            risk_tier: string;
            /** Anomaly Score */
            anomaly_score: number;
            /** Anomaly Flagged */
            anomaly_flagged: boolean;
            /** Is Flagged */
            is_flagged: boolean;
            /** Top Prediction Drivers */
            top_prediction_drivers: components["schemas"]["ShapDriver"][];
            /** Top Anomaly Drivers */
            top_anomaly_drivers?: components["schemas"]["ShapDriver"][] | null;
            /** Reviewer Note */
            reviewer_note: string;
            /** Audit History */
            audit_history: components["schemas"]["AuditEntry"][];
        };
        /** LoanListItem */
        LoanListItem: {
            /** Loan Id */
            loan_id: string;
            /** Region */
            region: string;
            /** Loan Type */
            loan_type: string;
            /** Loan Amount */
            loan_amount: number;
            /** Calibrated Probability */
            calibrated_probability: number;
            /** Risk Tier */
            risk_tier: string;
            /** Anomaly Score */
            anomaly_score: number;
            /** Anomaly Flagged */
            anomaly_flagged: boolean;
            /** Is Flagged */
            is_flagged: boolean;
        };
        /** LoanListResponse */
        LoanListResponse: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Items */
            items: components["schemas"]["LoanListItem"][];
        };
        /** PortfolioSummaryResponse */
        PortfolioSummaryResponse: {
            /** N Loans */
            n_loans: number;
            /** Total Portfolio Expected Loss */
            total_portfolio_expected_loss: number;
            /** Average Calibrated Probability */
            average_calibrated_probability: number;
            /** Risk Tier Breakdown */
            risk_tier_breakdown: components["schemas"]["RiskTierBucket"][];
            /** Flagged Loan Count */
            flagged_loan_count: number;
            /** Flagged Loan Pct */
            flagged_loan_pct: number;
            anomaly: components["schemas"]["AnomalyBreakdown"];
            reviewer: components["schemas"]["ReviewerStats"];
            scenario_comparison?: components["schemas"]["ScenarioComparison"] | null;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "override";
            /** Reason */
            reason?: string | null;
        };
        /** ReviewResponse */
        ReviewResponse: {
            /** Loan Id */
            loan_id: string;
            /** Decision */
            decision: string;
            /** Reason */
            reason: string;
            /** Flag Event Type */
            flag_event_type: string;
            /** References Hash */
            references_hash: string;
            /** Entry Hash */
            entry_hash: string;
        };
        /** ReviewerStats */
        ReviewerStats: {
            /** N Reviews */
            n_reviews: number;
            /** N Overrides */
            n_overrides: number;
            /** Override Rate */
            override_rate?: number | null;
        };
        /** RiskTierBucket */
        RiskTierBucket: {
            /** Tier */
            tier: string;
            /** Count */
            count: number;
            /** Pct Of Portfolio */
            pct_of_portfolio: number;
        };
        /** ScenarioComparison */
        ScenarioComparison: {
            /** Scenario File */
            scenario_file: string;
            /** N Loans In Current Book */
            n_loans_in_current_book: number;
            /** Baseline Expected Loss */
            baseline_expected_loss: number;
            /** Shocked Expected Loss */
            shocked_expected_loss: number;
            /** Delta */
            delta: number;
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /** Feature */
            feature: string;
            /** Shock */
            shock: number;
            /** Region */
            region?: string | null;
        };
        /** ScenarioRunResponse */
        ScenarioRunResponse: {
            /** Shock Type */
            shock_type: string;
            /** Magnitude */
            magnitude: number;
            /** Region */
            region?: string | null;
            /** Expected Loss Before */
            expected_loss_before: number;
            /** Expected Loss After */
            expected_loss_after: number;
            /** Expected Loss Delta */
            expected_loss_delta: number;
            /** Portfolio Mean Proba Before */
            portfolio_mean_proba_before: number;
            /** Portfolio Mean Proba After */
            portfolio_mean_proba_after: number;
            /** Top Movers */
            top_movers: components["schemas"]["ScenarioTopMover"][];
        };
        /** ScenarioTopMover */
        ScenarioTopMover: {
            /** Loan Id */
            loan_id: string;
            /** Region */
            region: string;
            /** Loan Type */
            loan_type: string;
            /** Proba Before */
            proba_before: number;
            /** Proba After */
            proba_after: number;
            /** Delta */
            delta: number;
        };
        /** ShapDriver */
        ShapDriver: {
            /** Feature */
            feature: string;
            /** Shap Value */
            shap_value: number;
            /** Value */
            value: number | string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    portfolio_summary_portfolio_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummaryResponse"];
                };
            };
        };
    };
    list_loans_loans_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number */
                page?: number;
                page_size?: number;
                risk_tier?: ("low" | "medium" | "high") | null;
                region?: string | null;
                loan_type?: string | null;
                /** @description filter to loans currently flagged (high risk tier or top-1% anomaly) */
                flagged?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loan_loans__loan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_loan_loans__loan_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_run_scenario_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRunResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPError"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_verify_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditVerifyResponse"];
                };
            };
        };
    };
    audit_entries_audit_entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
        };
    };
}
